タイトルシーンの作成
Kinoshita-Tatsuya/SmokeSheep pull request #4
Opened 2019-02-22 11:04 UTC by Kinoshita-Tatsuya

#3 
背景の描画

2019-02-22 11:27 UTC, Harutaka-Tsujino approved these changes
確認しました

2019-02-24 10:21 UTC, Kinoshita-Tatsuya commented
タイトルシーンの完成したので、レビューお願いします

2019-02-24 10:24 UTC, Harutaka-Tsujino requested changes

2019-02-24 10:24 UTC, Harutaka-Tsujino commented on SmokeSheep/SmokeSheep/class/SceneManager/Scene/TitleScene/TitileObj/TitleAnimations/TitleAnimations.cpp
> +	static int count = 0;
どのような使用目的で扱われるかが分かりにくいです

2019-02-24 10:35 UTC, Harutaka-Tsujino commented on SmokeSheep/SmokeSheep/class/SceneManager/Scene/TitleScene/TitileObj/TitleAnimations/TitleAnimations.cpp
> +	static int count = 0;
countのほうです

2019-02-24 10:37 UTC, Harutaka-Tsujino approved these changes
確認しました

2019-02-24 12:04 UTC, ToshiyaMatsuoka commented on SmokeSheep/SmokeSheep/class/SceneManager/Scene/TitleScene/TitileObj/TitleAnimations/TitleAnimations.cpp
> +	m_rGameLib.CreateTex(m_filePathAndKeys[TA_SHEEP][0], m_filePathAndKeys[TA_SHEEP][1]);
```
m_rGameLib.CreateTex(m_filePathAndKeys[TA_SHEEP][0], m_filePathAndKeys[TA_SHEEP][1]);
```
テクスチャ作るたびにいちいち2次の配列の後ろに0か1を入れるのであれば定数などにしておくべきだと思います。

そもそも一つ目のTA_SHEEPなどの値が決まれば、それで実行する関数作ればいいと思いますけど

2019-02-24 12:04 UTC, ToshiyaMatsuoka commented on SmokeSheep/SmokeSheep/class/SceneManager/Scene/TitleScene/TitileObj/TitleAnimations/TitleAnimations.cpp
> +	startTU = (IMAGE_SIZE * m_animationCounts[TA_SHEEP]) / MAX_IMAGE_SIZE;
```suggestion

const float 一枚目のUVの幅 = (IMAGE_SIZE / MAX_IMAGE_SIZE) 
startTU = 一枚目のUVの幅* m_animationCounts[TA_SHEEP];
```
上記のようにするといちいち計算処理しなくなるので個人的には好きな方法です。

2019-02-26 05:29 UTC, Kinoshita-Tatsuya commented on SmokeSheep/SmokeSheep/class/SceneManager/Scene/TitleScene/TitileObj/TitleAnimations/TitleAnimations.cpp
> +	m_rGameLib.CreateTex(m_filePathAndKeys[TA_SHEEP][0], m_filePathAndKeys[TA_SHEEP][1]);
ファイルパスとキーの文字列を分けて1次元配列にします

2019-02-26 05:31 UTC, Kinoshita-Tatsuya commented on SmokeSheep/SmokeSheep/class/SceneManager/Scene/TitleScene/TitileObj/TitleAnimations/TitleAnimations.cpp
> +	startTU = (IMAGE_SIZE * m_animationCounts[TA_SHEEP]) / MAX_IMAGE_SIZE;
その方法にします
ありがとうございます

2019-02-26 07:27 UTC, yttmwork reviewed
マジックナンバーが残っていたので指摘しました。

2019-02-26 07:27 UTC, yttmwork commented on SmokeSheep/SmokeSheep/class/SceneManager/Scene/TitleScene/TitileObj/TitleSelectMenu/TitleSelectMenu.cpp
> +		m_rGameLib.Render(font, m_rGameLib.GetTex(m_fileKeys[i + 2]));
このファイルでは、ここやその他の場所で「2」という数字が目に付きます。
これらは同じ意味を持っていると思われますが、どうでしょうか？
もし、同じ意味ならば定数化を行ってください。

2019-02-26 08:06 UTC, Kinoshita-Tatsuya commented on SmokeSheep/SmokeSheep/class/SceneManager/Scene/TitleScene/TitileObj/TitleSelectMenu/TitleSelectMenu.cpp
> +		m_rGameLib.Render(font, m_rGameLib.GetTex(m_fileKeys[i + 2]));
enumで列挙した変数があるので、それを使うようにします。

2019-02-26 08:21 UTC, yttmwork approved these changes
指摘部分確認しました。

2019-02-27 03:58 UTC, ToshiyaMatsuoka approved these changes
修正確認しました。

2019-02-27 04:09 UTC, merged